### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by romantictravel** [chenggangpro/spring-cloud-gateway-plugin#22]
文档太精简了,看不懂,特别是针对路由的,大体的意思是根据请求参数键值对匹配到不同的服务去
eureka中的meta-map有什么用

**Comment by chenggangpro** [comment]
eureka中的meta-data中的version，与配置在网关上的version做匹配，匹配到了则路由到对应version的服务中，这是基于ribbon断言的路由方式，与zuul上动态路由一致

**Comment by chenggangpro** [comment]
no feedback after 7 days
