### ISSUE TITLE
建议分成2个jar

### ISSUE THREAD

**Issue by romantictravel** [chenggangpro/spring-cloud-gateway-plugin#23]
路由相关的一个jar,其他基础功能一个jar,因为不一定会用到hysrix和eureka,引用起来方便

**Comment by chenggangpro** [comment]
现在是支持的，hystrix和eureka依赖都是optional的，只要不引入依赖就不会加载，同样，不开启配置，也不会加载

**Comment by chenggangpro** [comment]
no feedback after 7 days
