### ISSUE TITLE
灰度发布支持Nacos吗？

### ISSUE THREAD

**Issue by staticLin** [chenggangpro/spring-cloud-gateway-plugin#37]
作者你好，我看了您的源代码，发现这里的灰度发布是配合了eureka的元数据功能去选择不同的实例，想问一下Nacos也有相关的方式去获取服务实例的元数据，达到同样的灰度发布的效果吗？

**Comment by SyloYamtao** [comment]
暂不支持

**Comment by staticLin** [comment]
现已解决问题。很感谢作者贡献的源码，Nacos也可以按照一定思路拿到元数据。
close issue
